spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arpanel07@gmail.com
spring.mail.password=mjas zxoq xydv sqcq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#mongodb+srv://helpifyuni_db_user:E30Xldttt2uobUwQ@helpify.5lmpbwi.mongodb.net/?appName=Helpify
# MongoDB Atlas Connection
spring.mongodb.uri=mongodb+srv://helpifyuni_db_user:E30Xldttt2uobUwQ@helpify.5lmpbwi.mongodb.net/helpify?retryWrites=true&w=majority&appName=Helpify